opensourceways/datastat-server

- src/main/java/com/datastat/config/MindSporeConfig.java
- src/main/java/com/datastat/config/OpenEulerConfig.java
- src/main/java/com/datastat/config/OpenGaussConfig.java
- src/main/java/com/datastat/config/OpenLookengConfig.java
- src/main/java/com/datastat/config/QueryConfig.java
- src/main/java/com/datastat/config/context/QueryConfContext.java
- src/main/java/com/datastat/model/CustomPropertiesConfig.java
> config and model Autowired

- src/main/java/com/datastat/model/BlueZoneUser.java
- src/main/java/com/datastat/model/SigDetails.java
- src/main/java/com/datastat/model/SigDetailsMaintainer.java
- src/main/java/com/datastat/model/TokenUser.java
- src/main/java/com/datastat/model/UserTagInfo.java
- src/main/java/com/datastat/model/vo/BlueZoneContributeVo.java
- src/main/java/com/datastat/model/vo/BlueZoneUserVo.java
- src/main/java/com/datastat/model/vo/BuildCheckInfoQueryVo.java
- src/main/java/com/datastat/model/vo/IsoBuildTimesVo.java
- src/main/java/com/datastat/model/vo/PrReviewerVo.java
- src/main/java/com/datastat/model/vo/SigDetailsVo.java
- src/main/java/com/datastat/model/yaml/CommunityPartnersYaml.java
- src/main/java/com/datastat/model/yaml/CommunityPartnersYamlInfo.java
- src/main/java/com/datastat/model/yaml/CompanyYaml.java
- src/main/java/com/datastat/model/yaml/CompanyYamlInfo.java
- src/main/java/com/datastat/model/yaml/GroupYamlInfo.java
- src/main/java/com/datastat/model/yaml/SigYaml.java
- src/main/java/com/datastat/model/yaml/SigYamlInfo.java
- src/main/java/com/datastat/result/ResponseAdvice.java
- src/main/java/com/datastat/result/ResultData.java
- src/main/java/com/datastat/result/ReturnCode.java
> add models

- src/main/java/com/datastat/interceptor/authentication/AuthenticationInterceptor.java
- src/main/java/com/datastat/interceptor/authentication/InterceptorConfig.java
- src/main/java/com/datastat/interceptor/authentication/PassToken.java
- src/main/java/com/datastat/interceptor/authentication/UserLoginToken.java
- src/main/java/com/datastat/interceptor/oneid/CompanyToken.java
- src/main/java/com/datastat/interceptor/oneid/OneidInterceptor.java
- src/main/java/com/datastat/interceptor/oneid/OneidInterceptorConfig.java
- src/main/java/com/datastat/interceptor/oneid/OneidToken.java
- src/main/java/com/datastat/interceptor/oneid/OneidUserToken.java
- src/main/java/com/datastat/interceptor/oneid/SigToken.java
> add interceptor

- src/main/java/com/datastat/service/JwtTokenCreateService.java
- src/main/java/com/datastat/service/QueryService.java
- src/main/java/com/datastat/service/TokenUserService.java
> add service

- src/main/java/com/datastat/config/OpenGaussConfig.java
- src/main/java/com/datastat/controller/QueryController.java
- src/main/java/com/datastat/dao/QueryDao.java
- src/main/java/com/datastat/model/CustomPropertiesConfig.java
- src/main/java/com/datastat/model/yaml/UserInfoYaml.java
- src/main/java/com/datastat/model/yaml/UserNameYaml.java
- src/main/java/com/datastat/service/QueryService.java
- src/main/java/com/datastat/util/EsQueryUtils.java
> add gitee webhook test

- src/main/java/com/datastat/controller/QueryController.java
> gitee webhook test

- src/main/java/com/datastat/controller/QueryController.java
- src/main/java/com/datastat/dao/QueryDao.java
- src/main/java/com/datastat/model/CustomPropertiesConfig.java
- src/main/java/com/datastat/service/QueryService.java
> parse gitee webhook user

- src/main/java/com/datastat/service/QueryService.java
> gitee action webhook

- src/main/java/com/datastat/controller/QueryController.java
- src/main/java/com/datastat/dao/QueryDao.java
- src/main/java/com/datastat/model/CustomPropertiesConfig.java
- src/main/java/com/datastat/service/QueryService.java
update id of gitee webHook user
> update id of gitee webHook user

- src/main/java/com/datastat/dao/QueryDao.java
- src/main/java/com/datastat/util/RestHighLevelClientUtil.java
> update es high level client

- src/main/java/com/datastat/dao/QueryDao.java
add pr/issue count for open-source
> add pr/issue count for open-source

- src/main/java/com/datastat/dao/QueryDao.java
change aggregated community to LowerCase for open-source
> change aggregated community to LowerCase for open-source

- src/main/java/com/datastat/dao/QueryDao.java
唯一变化是：new String(Base64.getDecoder().decode(data));变成new String(Base64.getDecoder().decode(data), "utf-8");
> 更新编码格式，测试能否解决乱码问题

- Dockerfile
- src/main/java/com/datastat/dao/QueryDao.java
在Linux开发机里修改Dockerfile中语言环境，成功解决乱码问题。
> second try to fix /track

- Dockerfile
- pom.xml
- src/main/java/com/datastat/dao/QueryDao.java
1：为了解决/track接口编码错误问题，在QueryDao.java中添加System.out.println()语句。现在解决了问题，将这些语句删除。
2：将docker中maven源替换为清华源。在Dockerfile中更换maven源为清华源，在pom.xml中更改项目插件、maven插件的源为阿里源。
> update /track and change maven source

- src/main/java/com/datastat/controller/QueryController.java
> test api /all

- src/main/java/com/datastat/controller/QueryController.java
- src/main/java/com/datastat/model/CustomPropertiesConfig.java
1 fix the api /all
之前测试/all接口，输出时间信息。现在问题解决，删除时间输出语句。
2 修复bug
之前我误将CustomPropertiesConfig.java类中getAggCommentQueryStr()方法修改了，原因是我新写的方法与这个方法结构类似，并未分辨出该方法并不是我写的。该方法在其他接口都没有用到，修改本方法代码不影响其他接口。现在将该方法回滚到之前的版本。
> fix the api /all and fix bug

- src/main/java/com/datastat/interceptor/oneid/OneidInterceptor.java
> test api/sig/score

- src/main/java/com/datastat/interceptor/oneid/OneidInterceptor.java
> try third to fix the bug of /score

- src/main/java/com/datastat/dao/MindSporeQueryDao.java
- src/main/java/com/datastat/dao/QueryDao.java
- src/main/java/com/datastat/interceptor/oneid/OneidInterceptor.java
1 在dao层更新updateat字段
2 删除OneidInterceptor.java中的日志输出语句
> add updateat

- src/main/java/com/datastat/controller/QueryController.java
- src/main/java/com/datastat/dao/QueryDao.java
- src/main/java/com/datastat/model/CustomPropertiesConfig.java
- src/main/java/com/datastat/model/SearchIssueBody.java
- src/main/java/com/datastat/service/QueryService.java
[多社区对搜索结果的反馈类似，因此选择将函数进行聚合，分社区进行反馈。
> openeuler增加搜索反馈
